# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026  Nicolas Gabriel Cotti

name: Markdown Linter
description: Enforces Markdown linter.

inputs:
  target_dir:
    description: "Root directory to parse files"
    required: true
    type: string
  config_file:
    description: ".markdownlint-cli2.jsonc file path inside your repo"
    default: "cotti-ci/default_config/.markdownlint-cli2.jsonc"
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: "Checkout cotti-ci"
      uses: actions/checkout@v5
      with:
        repository: ncotti/cotti-ci
        path: cotti-ci

    - name: "Markdown linter script"
      shell: bash
      run: |
        chmod +x cotti-ci/scripts/markdown_lint.sh
        cotti-ci/scripts/markdown_lint.sh ${{ inputs.target_dir}} ${{ inputs.config_file }}
