# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026  Nicolas Gabriel Cotti

name: Markdown Linter
description: Enforces Markdown linter.

inputs:
  target_dir:
    description: "Root directory to parse files"
    required: true
    type: string
  config_file:
    description: ".markdownlint-cli2.jsonc file path inside your repo"
    default: "${{ github.action_path }}/default_config/.markdownlint-cli2.jsonc"
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: "Markdown linter script"
      shell: bash
      run: |
        printf "${{ github.action_path }}\n"
        ls "${{ github.action_path }}"
        chmod +x "${{ github.action_path }}/scripts/markdown_lint.sh"
        "${{ github.action_path }}/scripts/markdown_lint.sh" \
          "${{ inputs.target_dir }}" \
          "${{ inputs.config_file }}"
