# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026  Nicolas Gabriel Cotti

name: Bash linter
description: >
  Uses shellcheck to check that bash scripts are ok.
  Extensions checked: .sh, .bash, .bats

inputs:
  target_dir:
    description: "Root directory to parse files"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: "Run shellcheck"
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/scripts/bash_lint.sh"
        ${{ github.action_path }}/scripts/bash_lint.sh \
          "${{ inputs.target_dir }}"
