# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026  Nicolas Gabriel Cotti

name: BATS (Bash Automated Testing System) tester
description: >
  Uses bats

inputs:
  target_dir:
    description: "Root directory where .bats files are located"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: "Run bats tests"
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/../../scripts/bats_test.sh"
        "${{ github.action_path }}/../../scripts/bats_test.sh" \
          "${{ inputs.target_dir }}"
