# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026  Nicolas Gabriel Cotti

name: BATS (Bash Automated Testing System) tester
description: >
  Uses bats

inputs:
  target_dir:
    description: "Root directory where .bats files are located"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: "Checkout cotti-ci"
      uses: actions/checkout@v5
      with:
        repository: ncotti/cotti-ci
        path: "${{ runner.temp }}/cotti-ci"

    - name: "Run bats tests"
      shell: bash
      run: |
        chmod +x "${{ runner.temp }}/cotti-ci/scripts/bats_test.sh"
        "${{ runner.temp }}/cotti-ci/scripts/bats_test.sh" \
          "${{ inputs.target_dir }}"
